// Noms utilisés pour les pseudos
export const nouns = [
	'Charles de Gaulle',
    'Louis Pasteur',
    'Abbé Pierre',
    'Marie Curie',
    'Coluche',
    'Victor Hugo',
    'Bourvil',
    'Molière',
    'Jacques-Yves Cousteau',
    'Édith Piaf',
    'Marcel Pagnol',
    'Georges Brassens',
    'Fernandel',
    'Jean de La Fontaine',
    'Jules Verne',
    'Napoléon Bonaparte',
    'Louis de Funès',
    'Jean Gabin',
    'Daniel Balavoine',
    'Serge Gainsbourg',
    'Zinédine Zidane',
    'Charlemagne',
    'Lino Ventura',
    'François Mitterrand',
    'Gustave Eiffel',
    'Émile Zola',
    'Sœur Emmanuelle',
    'Jean Moulin',
    'Charles Aznavour',
    'Yves Montand',
    "Jeanne d'Arc",
    'Maréchal Leclerc',
    'Voltaire',
    'Johnny Hallyday',
    'Antoine de Saint-Exupéry',
    'Claude François',
    'Christian Cabrol',
    'Jean-Paul Belmondo',
    'Jules Ferry',
    'Louis Lumière',
    'Jacques Chirac',
    'Charles Trenet',
    'Georges Pompidou',
    'Michel Sardou',
    'Simone Signoret',
    'Haroun Tazieff',
    'Jacques Prévert',
    'Éric Tabarly',
    'Louis XIV',
    'David Douillet',
    'Henri Salvador',
    'Jean-Jacques Goldman',
    'Jean Jaurès',
    'Jean Marais',
    'Yannick Noah',
    'Albert Camus',
    'Dalida',
    'Léon Zitrone',
    'Nicolas Hulot',
    'Simone Veil',
    'Alain Delon',
    "Patrick Poivre d'Arvor",
    "Aimé Jacquet",
    'Francis Cabrel',
    'Brigitte Bardot',
    'Guy de Maupassant',
    'Alexandre Dumas',
    'Honoré de Balzac',
    'Paul Verlaine',
    'Jean-Jacques Rousseau',
    'Maximilien de Robespierre',
    'Renaud',
    'Bernard Kouchner',
    'Claude Monet',
    'Michel Serrault',
    'Auguste Renoir',
    'Michel Drucker',
    'Raimu',
    'Vercingétorix',
    'Raymond Poulidor',
    'Charles Baudelaire',
    'Pierre Corneille',
    'Arthur Rimbaud',
    'Georges Clemenceau',
    'Gilbert Bécaud',
    'José Bové',
    'Jean Ferrat',
    'Henri Matisse',
    'Lionel Jospin',
    'Jean Cocteau',
    'Emile Durkheim',
    'Luc Besson',
    'Coco Chanel',
    'Tino Rossi',
    'Pierre de Coubertin',
    'Zinedine Zidane',
    'Jean Renoir',
    'Gérard Philipe',
    'Jean-Paul Sartre',
    'Maurice Ravel',
    'Catherine Deneuve',
    'Michel Foucault',
    'Serge Reggiani',
    'Gérard Depardieu',
    'Françoise Dolto',
    'Nicolas Sarkozy',
    'Victorien',
    'Paul',
    'Rémi',
    'Théo',
    'Clément',
    'Aimée',
    'Lucas',
    'Michel Platini',
    'Manu Chao',
    'Alain Prost',
    'Jean-Pierre Jeunet',
    'David Guetta',
    'Richard Clayderman'
]

export const possibleNouns = nouns;
